// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTFcKbpXksoRcbTv8-pParzTm78hS6b6U',
    appId: '1:625588123137:web:39371ff0bf2a31eb96b200',
    messagingSenderId: '625588123137',
    projectId: 'projetopuc-c602e',
    authDomain: 'projetopuc-c602e.firebaseapp.com',
    databaseURL: 'https://projetopuc-c602e-default-rtdb.firebaseio.com',
    storageBucket: 'projetopuc-c602e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaYjm-LtnmbtUThMsYiN460QbkOKbOznM',
    appId: '1:625588123137:android:d845f1ec941fccfe96b200',
    messagingSenderId: '625588123137',
    projectId: 'projetopuc-c602e',
    databaseURL: 'https://projetopuc-c602e-default-rtdb.firebaseio.com',
    storageBucket: 'projetopuc-c602e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKAYKLeQXXCmSr6t_VSoaLvHgEShlBw8',
    appId: '1:625588123137:ios:adccf1af2c99724e96b200',
    messagingSenderId: '625588123137',
    projectId: 'projetopuc-c602e',
    databaseURL: 'https://projetopuc-c602e-default-rtdb.firebaseio.com',
    storageBucket: 'projetopuc-c602e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOKAYKLeQXXCmSr6t_VSoaLvHgEShlBw8',
    appId: '1:625588123137:ios:adccf1af2c99724e96b200',
    messagingSenderId: '625588123137',
    projectId: 'projetopuc-c602e',
    databaseURL: 'https://projetopuc-c602e-default-rtdb.firebaseio.com',
    storageBucket: 'projetopuc-c602e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTFcKbpXksoRcbTv8-pParzTm78hS6b6U',
    appId: '1:625588123137:web:4491e33af13311bf96b200',
    messagingSenderId: '625588123137',
    projectId: 'projetopuc-c602e',
    authDomain: 'projetopuc-c602e.firebaseapp.com',
    databaseURL: 'https://projetopuc-c602e-default-rtdb.firebaseio.com',
    storageBucket: 'projetopuc-c602e.firebasestorage.app',
  );
}
